[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false
evm_version = "paris"
fuzz = { runs = 1024 } # fuzzy runs more then default 256
gas_reports = [""]
libs = ['lib']

optimizer = true
optimizer-runs = 10_000_000
# via-ir = true

out = 'out'
script = 'script'
solc = "0.8.19"
src = 'src'
test = 'test'
verbosity = 3 # logs by default

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4


# https://book.getfoundry.sh/cheatcodes/rpc
[etherscan]
# arbitrum_one = { key = "${API_KEY_ARBISCAN}" }
# avalanche = { key = "${API_KEY_SNOWTRACE}" }
# bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
# gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
goerli = { key = "${API_KEY_ETHERSCAN}" }
mainnet = { key = "${API_KEY_ETHERSCAN}" }
# optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
# polygon = { key = "${API_KEY_POLYGONSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }


[rpc_endpoints]
# arbitrum_one = "${ARBITRUM_RPC_URL}"
# avalanche = "${AVALANCHE_RPC_URL}"
# bnb_smart_chain = "${BSC_RPC_URL}"
# chiado = "${CHIADO_RPC_URL}"
# gnosis_chain = "${GNOSIS_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
localhost = "http://localhost:8545"
mainnet = "${ETH_MAINNET_RPC_URL}"
# optimism = "${OPTIMISM_RPC_URL}"
# polygon = "${POLYGON_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
# multiline_func_header = "all"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
wrap_comments = true
ignore = []

[doc]
title = "xToken"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
